import { Montserrat } from "next/font/google";
import "./globals.css";
import Nav from "./components/Nav/Nav";
import Footer from "./components/Footer/Footer";
import Theme from "./components/context/theme";
const bodyFont = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={bodyFont.className}>
        <Theme>
          <div className="container">
            <Nav />
            {children}

            <Footer />
          </div>
        </Theme>
      </body>
    </html>
  );
}
